command = "/opt/navidrome"

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[environment]
additional = { ND_MUSICFOLDER = "/music", ND_DATAFOLDER = "/data", ND_CONFIGFILE = "/data/navidrome.toml", ND_PORT = "8080", ND_SCANNER_ENABLED = "false", ND_SCANNER_SCANONSTARTUP = "false" }
keep-env = true
